site_name: Lyon 2 SISE Tutorials
theme:
  name: material
  palette:
    primary: custom

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Overview: index.md
  - 0 - Prerequisites: prerequisites.md
  - 1 - MLOps: mlops.md
  - 2 - NoSQL: nosql.md
  - 3 - Spark: spark.md
  - 4 - GenAI: genai.md

copyright: Copyright &copy; 2024 Fanilo ANDRIANASOLO